lambda_role_name   = "resume_challenge_role"
lambda_policy_name = "resume_challenge_policy"
name_dynamodb      = "Resumes"
project_name       = "resume_challenge"
function_name      = "resume_challenge_lamda_function"
region             = "ca-central-1"